# Generated by Django 6.1.1 on 2026-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='status',
            field=models.CharField(choices=[('FREE', 'Свободен'), ('BUSY', 'Занят'), ('VACATION', 'В отпуске')], default='FREE'),
        ),
    ]
