# Generated by Django 6.1.1 on 2026-09-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='desceiption',
            new_name='description',
        ),
    ]
